(() => {
  const FUNCTION_URL = window.TALISM_AI_FUNCTION_URL || `${window.TALISM_SUPABASE_URL}/functions/v1/ask-talis`;
  const style = document.createElement('style');
  style.textContent = `.talism-ai-launcher{position:fixed;right:22px;bottom:22px;z-index:50;border:0;border-radius:999px;background:#292326;color:#fff;padding:14px 18px;box-shadow:0 12px 30px #30232933;font:600 12px 'DM Sans',sans-serif;letter-spacing:.08em;cursor:pointer}.talism-ai-panel[hidden]{display:none!important}.talism-ai-panel{position:fixed;right:22px;bottom:78px;z-index:51;width:min(370px,calc(100vw - 28px));height:min(560px,calc(100vh - 110px));display:flex;flex-direction:column;border:1px solid #e6dede;border-radius:16px;background:#fffdfb;box-shadow:0 20px 70px #30232933;overflow:hidden;font-family:'DM Sans',sans-serif}.talism-ai-head{display:flex;align-items:center;justify-content:space-between;background:#292326;color:#fff;padding:16px 18px}.talism-ai-head strong{font-family:'Playfair Display',serif;font-size:19px;font-weight:600}.talism-ai-close{border:0;background:none;color:#fff;font-size:20px;cursor:pointer}.talism-ai-messages{flex:1;overflow:auto;padding:16px;background:#fbf8f6}.talism-ai-message{max-width:86%;margin:0 0 12px;padding:10px 12px;border-radius:12px;font-size:13px;line-height:1.55;white-space:pre-wrap}.talism-ai-message.assistant{background:#fff;border:1px solid #e8dfe0;color:#4e4447}.talism-ai-message.user{margin-left:auto;background:#ead7dc;color:#3e3034}.talism-ai-form{display:flex;gap:8px;padding:12px;border-top:1px solid #e6dede;background:#fff}.talism-ai-input{min-width:0;flex:1;border:1px solid #ddcfd1;border-radius:9px;padding:10px;font:13px 'DM Sans',sans-serif}.talism-ai-send{border:0;border-radius:9px;background:#996c7a;color:#fff;padding:0 14px;font-weight:600;cursor:pointer}.talism-ai-send:disabled{opacity:.55;cursor:wait}@media(max-width:500px){.talism-ai-launcher{right:14px;bottom:14px}.talism-ai-panel{right:14px;bottom:70px}}`;
  document.head.appendChild(style);
  const launcher = document.createElement('button'); launcher.className = 'talism-ai-launcher'; launcher.textContent = 'ASK TALISM'; launcher.setAttribute('aria-label','Open TALISM customer assistant');
  const panel = document.createElement('section'); panel.className = 'talism-ai-panel'; panel.hidden = true; panel.innerHTML = `<header class="talism-ai-head"><strong>Ask TALISM</strong><button class="talism-ai-close" aria-label="Close assistant">×</button></header><div class="talism-ai-messages" aria-live="polite"><div class="talism-ai-message assistant">Welcome to TALISM. Ask me about our products, sizing, care, delivery, returns, or how to navigate the website.</div></div><form class="talism-ai-form"><input class="talism-ai-input" required maxlength="1200" placeholder="How may I help you?"><button class="talism-ai-send" type="submit">Send</button></form>`;
  document.body.append(launcher, panel);
  const messages = panel.querySelector('.talism-ai-messages'); const input = panel.querySelector('.talism-ai-input'); const send = panel.querySelector('.talism-ai-send'); const history = [];
  const addMessage = (content, role) => { const node = document.createElement('div'); node.className = `talism-ai-message ${role}`; node.textContent = content; messages.appendChild(node); messages.scrollTop = messages.scrollHeight; };
  launcher.onclick = () => { panel.hidden = !panel.hidden; if (!panel.hidden) input.focus(); }; panel.querySelector('.talism-ai-close').onclick = () => { panel.hidden = true; };
  panel.querySelector('form').onsubmit = async event => { event.preventDefault(); const question = input.value.trim(); if (!question || send.disabled) return; input.value = ''; addMessage(question, 'user'); history.push({ role:'user', content:question }); send.disabled = true; send.textContent = '…'; try { const response = await fetch(FUNCTION_URL, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ question, history: history.slice(-6) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Please try again.'); addMessage(result.answer, 'assistant'); history.push({ role:'assistant', content:result.answer }); } catch (error) { addMessage(error.message || 'The assistant is unavailable. Please use TALISM contact support.', 'assistant'); } finally { send.disabled = false; send.textContent = 'Send'; input.focus(); } };
})();
